title: Emma Mackay, MA, MSc
description: Statistical consultant specializing in Bayesian methods and causal inference for medical research
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
