title: Emma Mackay, MA, MSc, P.Stat.
description: Statistician and methodologist specializing in Bayesian methods and causal inference for medical research
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
